config/routes.rb
Agreedupon1::Application.routes.draw do
  resources :signed_urls, only: :index
  resources :users, path: 'foodies' do
    member do
      get :following, :followers, :ratings
    end
  end
  resource :image, :only => :new
  resources :sessions,      only: [:new, :create, :destroy]
  resources :activities,    only: [:new, :create, :destroy] 
  get 'tags/:tag', to: 'foods#show', as: :tag, 
                                     requirements: {:tag => /tag/i }
  resources :details  
  resources :ratings,       only: [:new, :create, :destroy, :update, :edit] do
    resources :lists
  end
  resources :relationships, only: [:create, :destroy]
  resources :product_types
  resources :foods,    path: 'food'
  resources :chefs,    path: 'chef'
  resources :cultures, path: 'culture'
  resources :cuisines, path: 'cuisine'
  resources :user_profiles
  root to: 'home#index', :controller => 'home'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/start',     to: 'static_pages#start',     via: 'get'
  match '/mission',   to: 'static_pages#mission',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/cultivate', to: 'static_pages#cultivate', via: 'get'
  match '/discover',  to: 'static_pages#discover',  via: 'get'
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController

  def index
    @activity = current_user.activities.build
    @product_types = ProductType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_types }
    end
  end

  def show
    @activity = current_user.activities.build
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @product_type }
    end
  end

  def new
    @activity = current_user.activities.build
    @product_type = ProductType.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_type }
    end
  end

  def edit
    @activity = current_user.activities.build
    @product_type = ProductType.find(params[:id])
  end

  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render json: @product_type, status: :created, location: @product_type }
      else
        format.html { render action: "new" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product_type = ProductType.find(params[:id])

    respond_to do |format|
      if @product_type.update_attributes(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type = ProductType.find(params[:id])
    @product_type.destroy

    respond_to do |format|
      format.html { redirect_to product_types_url }
      format.json { head :no_content }
    end
  end
  
  private 
  
    def product_type_params
      params.require(:product_type).permit(:name,
                                           fields_attributes: [:id, :name, :field_type, :required, :_destroy])
    end
end

app/views/product_types/_field_fields.html.erb
<fieldset>
  <%= f.select :field_type, %w[text_field check_box shirt_sizes] %>
  <%= f.text_field :name, placeholder: "field_name" %>
  <%= f.check_box :required %> <%= f.label :required %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/product_types/_form.html.erb
<%= form_for @product_type do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>
      <ul>
      <% @product_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :fields do |builder| %>
    <%= render 'field_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Field", f, :fields %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing product_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<h1>Listing product_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_types.each do |product_type| %>
  <tr>
    <td><%= product_type.name %></td>
    <td><%= link_to 'Show', product_type %></td>
    <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
    <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New product_type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product_type.name %>
</p>


<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>