config/routes.rb
Agreedupon1::Application.routes.draw do
  resources :signed_urls, only: :index
  resources :users, path: 'foodies' do
    member do
      get :following, :followers, :ratings
    end
  end
  resource :image, :only => :new
  resources :sessions,      only: [:new, :create, :destroy]
  resources :activities,    only: [:new, :create, :destroy] 
  get 'tags/:tag', to: 'foods#show', as: :tag, 
                                     requirements: {:tag => /tag/i }
  resources :details  
  resources :ratings,       only: [:new, :create, :destroy, :update, :edit] do
    resources :lists
  end
  resources :relationships, only: [:create, :destroy]
  resources :product_types
  resources :foods,    path: 'food'
  resources :chefs,    path: 'chef'
  resources :cultures, path: 'culture'
  resources :cuisines, path: 'cuisine'
  resources :user_profiles
  root to: 'home#index', :controller => 'home'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/start',     to: 'static_pages#start',     via: 'get'
  match '/mission',   to: 'static_pages#mission',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/cultivate', to: 'static_pages#cultivate', via: 'get'
  match '/discover',  to: 'static_pages#discover',  via: 'get'
end

app/models/culture.rb
class Culture < ActiveRecord::Base
  has_many :reverse_relationships, foreign_key: "culture_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  validates :name, uniqueness: { case_sensitive: false }
  
  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}")
    else
      all
    end
  end
  
  def slug
    name.downcase.gsub(" ", "-")
  end

  def to_param
    "#{id}-#{slug}"
  end
  
  def main_image
    self.image.nil? ? "default_food.png" : self.image
  end
end

app/controllers/cultures_controller.rb
class CulturesController < ApplicationController
  before_action :signed_in_user
  before_action :admin_user, only: :edit
  
  def index
    @activity = current_user.activities.build
    @cultures = Culture.search(params[:search])
  end
  
  def show
    @activity = current_user.activities.build
    @culture = Culture.find(params[:id])
  end

  def new
    @activity = current_user.activities.build
    @culture = Culture.new  
    respond_to do |format|
      format.html
    end
  end
  
  def create
    @activity = current_user.activities.build
    @culture = Culture.new(culture_params)
    if @culture.save
      flash[:success] = "Enthused by #{@culture.name}"
      redirect_to culture_path
    else
      render 'new'
    end
  end
  
  def edit
    @activity = current_user.activities.build
    @culture = Culture.find_by_name(params[:id])
  end
  
  def update
    @culture = Culture.find_by_name(params[:id])
    if @culture.update_attributes(culture_params)
      flash[:success] = "culture profile updated"
      redirect_to @culture 
    else
      render 'edit'
    end
  end
  
  private 
  
    def culture_params
      params.require(:culture).permit(:name, :image, :thumbnail, :content)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    
end

app/views/cultures/_culture.html.erb
<li class="<%= culture_item.id %>">
	<% if !culture_item.image.blank? %>
		<div class="culture-image"> 

		</div>
	<% end %>
	<p class="cultureMeta">
		<h5>
			<%= link_to culture_item.name.downcase.humanize.singularize, culture_item, class: "culture-name" %>
		</h5>
	</p>
	<div class="clear"></div>
</li>

app/views/cultures/_follow.html.erb
<%= form_for(current_user.relationships.build(culture_id: @culture.id),
						 remote: true) do |f| %>
	<div><%= f.hidden_field :culture_id %></div>
	<%= f.submit "Follow", class: "btn btn-sm" %>
<% end %>

app/views/cultures/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
	<% if current_user.enthused_with?(@culture) %>
		<%= render 'unfollow' %>
	<% else %>
		<%= render 'follow' %>
	<% end %>
	</div>
<% end %>

app/views/cultures/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(culture_id: @culture),
						 html: { method: :delete },
						 remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-sm" %>
<% end %>

app/views/cultures/new.html.erb
<% if current_user.admin? %>

<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<%= form_for(@culture) do |f| %>

			<%= render 'shared/error_messages', object: f.object %>
			<%= render 'fields', f: f %>		
			<%= f.submit "Create culture", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

<% end %>

app/views/cultures/show.html.erb
<div class="row">
	<div>
		<h2 id="culture-name" class="culture-name"><%= @culture.name.titleize %></h2>
		<div class="col-sm-3 col-md-3 col-lg-3">
			<div id="culture-profile-image">
				<% if @culture.image.blank? %>
					<p style="font-size: 0.8em">(Beautiful image of culture coming soon)</p>
					<%= image_tag('default_culture.png') %>
				<% else %>
					<%= image_tag @culture.image_url(:thumbnail), class: "culture-profile-image",
																					alt: h(@culture.name) %>
				<% end %>
			</div>
			<%= render 'follow_form' %>
			<p id="culture-stats"><%= pluralize(@culture.followers.count, "Follower") %></p>
			<% if current_user.admin? %>
				<%= link_to "edit data", edit_culture_path(@culture) %>
			<% end %>
		</div>
		<div class="col-sm-8 col-md-8 col-lg-8" id="culture-description" >
			<h3 class="culture-profile">Culture Profile</h3>
			<p>Who What Where When Why How</p>
			<div class="panel-group" id="accordion">
				<div class="panel panel-default">
					<div class="panel-heading">
						<div class="panel-title">
							<h4><a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Top 3 Most Interesting Facts about <%= @culture.name %></a>
							</h4>
						</div>
					</div>
					<div class="panel-collapse collapse in" id="collapseOne">
						<div class="panel-body">
							<%= @culture.content%>
						</div>
					</div>
				</div>
			</div>
			<div class="panel-group" id="accordion">
				<div class="panel panel-default">
					<div class="panel-heading">
						<div class="panel-title">
							<h4><a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Health Benefits</a>
							</h4>
						</div>
					</div>
					<div class="panel-collapse collapse in" id="collapseTwo">
						<div class="panel-body">
							<%= @culture.content%>
						</div>
					</div>
				</div>
			</div>
					<!-- <ul><a>History</a></ul>
										<ul><a>Cultural Prevalence</a></ul>	 -->
			<div class="culture-posted">
				<h4 class="culture-profile">Recent Activity</h4>
				<p>Images shared by community so far</p>
				<p>People enthused with the culture so far</p>
				<p>Related links shared by community so far</p>
			</div>
		</div>
	</div>
</div>