config/routes.rb
Agreedupon1::Application.routes.draw do
  resources :signed_urls, only: :index
  resources :users, path: 'foodies' do
    member do
      get :following, :followers, :ratings
    end
  end
  resource :image, :only => :new
  resources :sessions,      only: [:new, :create, :destroy]
  resources :activities,    only: [:new, :create, :destroy] 
  get 'tags/:tag', to: 'foods#show', as: :tag, 
                                     requirements: {:tag => /tag/i }
  resources :details  
  resources :ratings,       only: [:new, :create, :destroy, :update, :edit] do
    resources :lists
  end
  resources :relationships, only: [:create, :destroy]
  resources :product_types
  resources :foods,    path: 'food'
  resources :chefs,    path: 'chef'
  resources :cultures, path: 'culture'
  resources :cuisines, path: 'cuisine'
  resources :user_profiles
  root to: 'home#index', :controller => 'home'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/start',     to: 'static_pages#start',     via: 'get'
  match '/mission',   to: 'static_pages#mission',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/cultivate', to: 'static_pages#cultivate', via: 'get'
  match '/discover',  to: 'static_pages#discover',  via: 'get'
end

app/views/shared/_delete.html.erb
<% if current_user?(object.user) %>
	<%= link_to "delete", object, class: "delete",
																method: :delete,
																data: { confirm: "You sure?" },
																title: object.content %>
<% end %>

app/views/shared/_direct_upload_form.html.erb
<form action="https://enthusedbyfood.s3.amazonaws.com/" method="post" enctype="multipart/form-data" class="direct-upload">
	<input type="hidden" name="key">
	<input type="hidden" name="acl" value="public-read"> 
	<input type="hidden" name="success_action_status" value="201">
   	<input type="hidden" name="X-Amz-Credential" value="<%= ENV['AWS_ACCESS_KEY_ID']%>/20180925/us-east-1/s3/aws4_request" />    
   	<input type="hidden" name="X-Amz-Algorithm" value="AWS4-HMAC-SHA256" /> 
   	<input type="hidden" name="X-Amz-Date" value="20180925T000000Z" /> 
	<input type="hidden" name="policy">
	<input type="hidden" name="X-Amz-Signature"/>     
	
	<p id="direct-upload-button">
		<span class="btn btn-file" id="button-cust" data-foodie-type="<%= data_object_type %>">OR click here to upload image
			<input type="file" name="file" id="file_input"> 
		</span>
	</p>
</form>

<div class="progress progress-striped active" id="<%= data_object_type %>" data-foodie-type="<%= data_object_type %>">
  <div class="progress-bar" id="<%= data_object_type %>" role="progressbar">
  </div>
</div>

app/views/shared/_favorites.html.erb
<ol>
	<li>Mom's Cooking</li>
	<li>Sushi</li>
</ol>
	

app/views/shared/_header_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div id="mission">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
					</button>
					<h3 id="myModalLabel">Recent Activity from Community</h3>
				</div><!-- ./modal-header -->
				<div class="modal-body">
					<p>
						Here are updates of recent activity from fellow foodies you are following. If they shared photos from an amazing restaurant they recently visited, or if they shared an interesting link about a new dish from their favorite chef, the post will show up on your activity feed. The goal here on enthusedbyfood.com is to catalog food from around the world and build the first user-generated food database. <br />

						We've made it easy to share what's enthused you in the world of food, as well as learn about the world through food. Food unites us all.
					</p>
				</div><!-- modal-body -->
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal">Close</button>
				</div><!-- modal-footer -->
			</div>
			<div id="cultivate">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
					</button>
					<h3 id="myModalLabel">Cultivate Foodie Database</h3>
				</div><!-- ./modal-header -->
				<div class="modal-body">
					<p>
						A dish, an ingredient, a cuisine, or culture sparked an interest? <br /> Cultivate your knowledge while cultivating the foodie database at the same time. Our belief is that this is your database. The more you cultivate it, the bigger and better it will be. Press the search bar next to the 'Cultivate' button, and enter something you were enthused by. If that item has already been cultivated, information about it will appear. 
					</p>
				</div><!-- modal-body -->
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal">Close</button>
				</div><!-- modal-footer -->
			</div>
			<div id="explore">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
					</button>
					<h3 id="myModalLabel">Explore the foodie community</h3>
				</div><!-- ./modal-header -->
				<div class="modal-body">
					<p>Look around the foodie community. See what foods, ingredients, and dishes have enthused fellow users. We've combed through yelp's data to see what is trending in the foodie community. Furthermore, you can see what enthused foodies are eating through their tags. Lastly, see what renowned chefs have joined our community.</p>
				</div><!-- /.modal-body -->
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal">Close</button>
				</div> <!-- /.modal-footer -->
			</div>
			<div id="discover">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
					</button>
					<h3 id="myModalLabel">Discover statement for enthused_by_food</h3>
				</div><!-- ./modal-header -->
				<div class="modal-body">
					<p>Part of our mission is to help you discover the world through food. Explore regions of the world, and the foodies in the region. Discover the food native to that region. </p>
				</div><!-- /.modal-body -->
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal">Close</button>
				</div> <!-- /.modal-footer -->
			</div>
			
			<div id="foodie">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
					</button>
					<h3 id="myModalLabel">User-generated content</h3>
				</div><!-- ./modal-header -->
				<div class="modal-body">
					<p>Your profile page with your recent activity, your stats, and of the foodies, chefs, ingredients, dishes, cuisines you are following. 
					Who doesn't love lists? Compile lists that further build the foodie database. Examples of lists: Your favorite ________ restaurants, Your favorite ingredients to use to cook with, Foods you have tried; Restaurants you want to check out. Lists can act a form of recommendation to friends and followers.</p>
				</div><!-- /.modal-body -->
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal">Close</button>
				</div> <!-- /.modal-footer -->
			</div>
						
		</div><!-- /.modal-content -->
	</div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->

app/views/shared/_modal.html.erb
<div id="myModal2" class="modal fade" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog" id="detailing">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h3 class="modal-title" id="myModalLabel">Your food adventure:</h3>
			</div> 
			
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal">Close</button>
				<button class="btn btn-primary">Save changes</button>
			</div>

		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_not_signed_in.html.erb
<div class="center hero-unit">
	<h1 class="logo">enthused by FOOD!</h1>
	<h2>
		Share all your food adventures!
	</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

</div>

app/views/shared/_pagination.html.erb
<ul class="pagination" id="pagination-index">
	<li><a href="./users?page=1">&laquo;</a></li>
	<li><a href="./users?page=1">1</a></li>
	<li><a href="./users?page=2">2</a></li>
	<li><a href="./users?page=3">3</a></li>
	<li><a href="./users?page=4">4</a></li>
	<li><a href="./users?page=4">&raquo;</a></li>
</ul>

app/views/shared/_photo_form.html.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.file_field :photo %> 
	</div>
	<div class="field">
		<%= f.submit 'Upload', class: "btn btn-large btn-success" %>
		<%= link_to 'Cancel', root_path, class: "btn btn-small btn-danger" %>
	</div>
<% end %>

app/views/shared/_post_modal.html.erb
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" 
aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h3 id="myModalLabel">Share something good!</h3>
			</div><!-- ./modal-header -->

			<div class="modal-body">
				<%= render 'shared/activity_form' %>
			</div><!-- ./modal-body -->

			<div class="modal-footer">
				<button class="btn" data-dismiss="modal">Close</button>
			</div> <!-- /.modal-footer -->
		</div>
	</div> <!-- /.modal-dialog -->
</div> <!-- /.modal -->
			
				
				
				
				
				
				

app/views/shared/_profileNav.html.erb
<div style="width: 100px; float: right; padding-top: 8px">
	<ul style="list-style: none">
		<li id="fat-menu" class="dropdown">
			<% if current_user.image.blank? %>
					<%= gravatar_for current_user, size: 52 %>
					<%= link_to current_user.name, @user %>
			<% else %>
				<a href="#" data-toggle="dropdown" id="hellothere">
				<%= image_tag current_user.image, width: '40px' %><b class="caret"></b>
				</a>
			<% end %>
			
			<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
				<li><%= link_to current_user.name, current_user, class: "dropdownLink" %></li>
				<li><%= link_to "edit settings", edit_user_path(current_user), class: "dropdownLink" %></li>
				<li class="divider"></li>
				<li>
					<%= link_to "sign out", signout_path, method: "delete", class: "dropdownLink" %>
				</li>
			</ul>
		</li>
	</ul>
</div>

app/views/shared/_restaurants.html.erb
<ul>Have checked out:
	<li>
		Eleven Madison Park
	</li>
	<li>
		Mission Cantina
	</li>
</ul>
<ul>Want to check out:
	<li>
		Per Se
	</li>
</ul>

app/views/shared/_signed_in.html.erb
<% if signed_in? %>
	<div class="row">
		<div class="col-12 col-sm-8 col-lg-8">
			<%= render 'shared/tree_item', collection: @tree_items %>
	</div>

</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<div class="stats foodies">
		<span>
			<a href="<%= following_user_path(@user) %>">
				<strong><span class="stat" id="following">
					Following: <br />
					<%= pluralize(@user.followed_users.count, "Foodie") %>
				</span></strong>
			</a>
		</span>
		<span>
			<a href="<%= followers_user_path(@user) %>">
				<strong><span class="stat" id="followers">
					Followed by: <br />
					<%= pluralize(@user.followers.count, "Foodie") %>
				</span></strong>
			</a>
		</span>
	</div>
	<div class="stats foods">
		<span class="stats_first">
			<a href="<%= user_path %>/following#followed_foods">
				<strong><span class="stat" id="following">
					Enthused with: <br />
					<%= pluralize(@user.followed_foods.count, "Food") %>
				</span></strong>
			</a>
		</span>
	</div>
	<div class="stats chefs">
		<span class="stats">
			<a href="<%= following_user_path(@user) %>">
				<strong><span class="stat" id="following">
					Enthused with: <br />
					<%= pluralize(@user.followed_chefs.count, "Chef") %>
				</span></strong>
			</a>
		</span>
	</div>
		
</div>

app/views/shared/_tree_item.html.erb
<li id="<%= tree_item.id %>">
	<div class="user">
		<span class="user_profile">
			<%= link_to (image_tag tree_item.user.image, width: '80px'), tree_item.user, id: "user_image"%>
		</span>
		<span>
			<% if current_user?(tree_item.user) %>
			<%= link_to "You", tree_item.user, class: 'link-class' %>
			<% else %>
			<%= link_to tree_item.user.name, tree_item.user, class: 'link-class' %>
			<% end %>
			<span class="timestamp tree_item">
				shared a <%= tree_item.type %> <%= time_ago_in_words(tree_item.created_at) %> ago.
			</span>
		</span>
	</div>
	
	<div>
		<span class="content"><%= tree_item.title %><span>
	</div>
	
	<% if tree_item.type == "link" %>
	<span>
		<a class="link" href=<%=tree_item.content%> target="_blank">
		<%= image_tag ("http://immediatenet.com/t/m?Size=1024x768&URL=" + tree_item.content) %>
		</a>
		<a class="link_text" href=<%= tree_item.content %>><%= tree_item.content %></a>
	</span>
	<% end %>
	
	<% unless tree_item.file.blank? %>
		<div class="img-responsive" id="photo" data-toggle="tooltip" title="<%= tree_item.content %>"><%= image_tag tree_item.file, class: "feed-photo" %>
		</div>	
	<% end %>
	<% unless tree_item.tag_list.blank? %>
	<div class="tagged">
		Tags: <%= raw tree_item.tag_list.map { |t| link_to t, food_path(t) }.join(', ') %>
	</div>
	<% end %>
	<div>
	<%= render 'shared/delete', object: tree_item %>
	</div>
	<p>
		<%= @filename %>
	</p>
</li>