config/routes.rb
Agreedupon1::Application.routes.draw do
  resources :signed_urls, only: :index
  resources :users, path: 'foodies' do
    member do
      get :following, :followers, :ratings
    end
  end
  resource :image, :only => :new
  resources :sessions,      only: [:new, :create, :destroy]
  resources :activities,    only: [:new, :create, :destroy] 
  get 'tags/:tag', to: 'foods#show', as: :tag, 
                                     requirements: {:tag => /tag/i }
  resources :details  
  resources :ratings,       only: [:new, :create, :destroy, :update, :edit] do
    resources :lists
  end
  resources :relationships, only: [:create, :destroy]
  resources :product_types
  resources :foods,    path: 'food'
  resources :chefs,    path: 'chef'
  resources :cultures, path: 'culture'
  resources :cuisines, path: 'cuisine'
  resources :user_profiles
  root to: 'home#index', :controller => 'home'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/start',     to: 'static_pages#start',     via: 'get'
  match '/mission',   to: 'static_pages#mission',   via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/cultivate', to: 'static_pages#cultivate', via: 'get'
  match '/discover',  to: 'static_pages#discover',  via: 'get'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :lists
  accepts_nested_attributes_for :lists, allow_destroy: true
  belongs_to :user
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :destroy, :edit]
  
  def new
    @rating = current_user.ratings.build
  end
  
  def create
    @rating = current_user.ratings.create!(ratings_params)
    respond_to do |format|
      format.html { redirect_to current_user }
      format.js
    end
  end
  
  def show
    @ratings = current_user.ratings
  end
  
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to current_user, notice: "Successfully destroyed list."
  end
  
  def update
    @rating = Rating.find(params[:id])
    if @rating.update_attributes(ratings_params)
      redirect_to ratings_user_path(current_user)
    end
  end
  
  def edit
    @activity = current_user.activities.build
    @rating = Rating.find(params[:id])
    @list = @rating.lists.find_by(rating_id: params[:id])
  end
  
  private 
  
    def ratings_params
      params.require(:rating).permit(:name,
                    lists_attributes: [:id, :name, :content, :_destroy])
    end
    
    def correct_user
      @rating = current_user.ratings.find_by(id: params[:id])
      redirect_to current_user if @rating.nil?
    end
end

app/views/ratings/_add_list.html.erb
<%= form_for @rating, remote: true do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div>
		<button type="button" class="close" aria-hidden="true">&times;</button>
	</div>
	<div class="field">
		<%= f.label :name, "Name of List:" %><br />
		<%= f.text_field :name %>
	</div>

	<div class="button">
		<%= f.submit "Add List", class: "btn btn-primary btn-success" %>
	</div>
	
<% end %>
<script>
$(function(){
	$("body").on("click", '.lists .close',
		function() {
			$('form#new_rating.new_rating').hide();
			$('a#new_link').show();
		}
	)}
);
</script>

app/views/ratings/_list_fields.html.erb
<fieldset>
	<% if @rating.lists.exists? %>
		<%= f.label :content, "On list so far:"%><br />
		<%= f.text_field :content, class: "list_field" %><br />
		<%= f.hidden_field :_destroy %>
		<%= link_to "Remove from List", '#', class: "remove_fields" %>
	<% else %>
		<%= f.label :content, "Add this to this list:" %><br />
		<%= f.text_field :content, class: "list_field" %><br />
		<%= f.check_box :_destroy %>
		<%= f.label :_destroy, "Remove from list" %> 
	<% end %>
</fieldset>

app/views/ratings/_rating.html.erb
<li class="ratings_list">
	<span>
		<%= @rating.name %>
		<%= link_to "(edit list)", edit_rating_path(@rating), class: 'list_edit' %>
	</span>
	<ol class="list details">
		<% @rating.lists.each do |list| %>
			<li>
				<%= list.content %>
			</li>
		<% end %>
	</ol>
</li>

app/views/ratings/create.js.erb
$('#new_rating').remove();
$('#new_link').show();
$('#ratings_lists').append('<%= j render(@rating) %>');
$('#empty').hide()

app/views/ratings/destroy.js.erb
$('#edit_rating_<%= @rating.id %>').remove();

app/views/ratings/edit.html.erb
<div class="row">
	<h2><%= @rating.name %></h2>
	
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @rating do |f| %>
		<div class="field">
			<%= f.label :name, "Name of List" %><br />
			<%= f.text_field :name %>
		</div>
		<%= link_to "(delete list)", @rating, method: :delete, data: {confirm: "Are you sure?"} %>

		<%= f.fields_for :lists do |builder| %>
		<%= render 'list_fields', f: builder %>
		<% end %>
		<%= link_to_add_fields "Add to List", f, :lists %>

		<div class="button">
			<%= f.submit "Save", class: "btn btn-primary btn-success", id: "save_button"%>
		</div>
		<% end %>
	</div>
	

</div>

<div class="row">
	<%= link_to "<-- Back to my lists", ratings_user_path(current_user) %>
</div>

app/views/ratings/new.html.erb
<h1>Lists</h1>

<%= render "ratings/add_list" %>

app/views/ratings/new.js.erb
$('#new_link').hide().after('<%= j render("ratings/add_list") %>');

app/views/ratings/update.js.erb
$('#edit_rating_<%= @rating.id %>').appendTo('#complete_tasks');